export const FETCH_ISSUES = 'FETCH_ISSUES';
export const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS';
export const SUBMIT_ISSUE = 'SUBMIT-ISSUE';
export const FETCH_ONE_ISSUE = 'FETCH_ONE_ISSUE';
export const UPDATE_ISSUE = 'UPDATE_ISSUE';